DiSSCo/openDS

Use-cases.md

A use case to help data curators track name changes and link rot.

 use case for taxonomic changes and collections data

---

Use-cases.md

A use case describing bird nest specimens, related eggs and anthropogenic materials found in the nest such as plastic water bottles.

add bird nest use case

---

data-model/annotations/schema/annotation.json

Few general fixes:
- Fix formatting according to DiSSCo practice
- fix missing namespace for "type"
- Add oa namespace to selector (should this be ods?)
- Capitalized constants "FieldValueSelector" and "ClassValueSelector"

Fix namespaces

---

data-model/annotations/schema/annotation.json

Add `generated` field. Fix "type" namespace.

add generated timestamp

---

data-model/annotations/schema/annotation.json

Aligns aggregation Rating with rfc.

aggregation namespace 

---

data-model/digital-specimen/schema/digital_specimen.json
data-model/digital-specimen/schema/identifications.json
data-model/digital-specimen/schema/occurrences.json

- Added additional dwc terms (mainly taxonomic terms)
- Moved two terms to specimen as I believe they fit better there
-

Add additional dwc terms

---

data-model/annotations/schema/annotation.json

Change ROI to Roi

---

data-model/annotations/schema/annotation.json

PR changes FieldValueSelector to FieldSelector and ClassValueSelector to ClassSelector based upon feedback from the community.
Requires changes in applications that use this part of the model.

Change FieldValueSelector and ClassValueSelector

---

data-model/annotations/schema/annotation.json

Fix namespace in required fields. Fix schema header

Namespace changes

---

data-model/annotations/schema/annotation.json

Added additional documentation:
- Descriptions with if possible linkages to the ontology
- Put things in constant when they appear to be constant
- Added examples so that it is clear what is expected
- Added enums when possible to limit the amount of possible values
- Added a comment on generated as this is not a valid oa term (not sure what to do yet)
Small changes
- `dcterms:reference` has become `dcterms:references` as this wasn't a valid dcterms term

Added documentation to schema and small changes

---

data-model/nginx/nginx.conf

nginx port

---

data-model/digitalobjects/0.1.0/digital-specimens/schema/chronometric-age.json
data-model/digitalobjects/0.1.0/digital-specimens/schema/material-entity.json
data-model/digitalobjects/0.1.0/digital-specimens/schema/occurrences.json

fix references

---

data-model/annotations/0.1.0/schema/annotations.json

Job ID will facilitate tracking batch annotations

Add job id to annotation model

---

data-model/fdo-profiles/0.1.0/README.md

short README to describe the FDO Profile schema.

Create a new README.md for FDO schema

---

data-model/fdo-profiles/0.1.0/virtualcollections/schema/virtualcollections.json

We can keep this simple -- only add ltc:collectionName, conditionofAccess and description. We could add measurementValue (to get the count) but these values will be dynamic so should not be in FDO record.

 virtualcollections FDO Record

---

data-model/fdo-profiles/0.1.0/source-system/schema/source-system-request.json
data-model/fdo-profiles/0.1.0/source-system/schema/source-system.json

Adds request and profile for source system pid records
note: If we use “allof”, we can’t generate code using our code gen library. Made a jira ticket to address other schemas to align them with this one

source system profile

---

data-model/fdo-type/create-update-tombstone-event/0.3.0/schema/create-update-tombstone.json
data-model/fdo-type/data-mapping/0.3.0/schema/data-mapping.json
data-model/fdo-type/digital-media/0.3.0/schema/digital-media.json
data-model/fdo-type/digital-specimen/0.3.0/schema/chronometric-age.json
data-model/fdo-type/digital-specimen/0.3.0/schema/digital-specimen.json
data-model/fdo-type/digital-specimen/0.3.0/schema/event.json
data-model/fdo-type/digital-specimen/0.3.0/schema/identification.json
data-model/fdo-type/digital-specimen/0.3.0/schema/location.json
data-model/fdo-type/digital-specimen/0.3.0/schema/material-entity.json
data-model/fdo-type/machine-annotation-service/0.3.0/schema/mas.json
data-model/fdo-type/shared-model/0.3.0/schema/agent.json
data-model/fdo-type/shared-model/0.3.0/schema/assertion.json
data-model/fdo-type/shared-model/0.3.0/schema/citation.json
data-model/fdo-type/shared-model/0.3.0/schema/entity-relationship.json
data-model/fdo-type/shared-model/0.3.0/schema/identifier.json
data-model/fdo-type/source-system/0.3.0/schema/source-system.json
data-model/fdo-type/tettris-service/0.1.0/schema/tettris-service.json
data-model/fdo-type/virtual-collection/0.1.0/schema/virtual-collection.json

Add title property to all schemas of latest version (3)

Add title property to all schemas of latest version (3)

---

data-model/fdo-type/digital-media/0.3.0/examples/digital-media-example.json
data-model/fdo-type/digital-media/0.3.0/examples/tombstoned-digital-media-example.json
data-model/fdo-type/digital-media/0.3.0/schema/digital-media.json

Requried for the Provenance record

Add source system id for digital media

---

data-model/fdo-type/tettris-service/0.1.0/schema/tettris-service.json

Update the JSON schema for the TETTRIs taxonomic service to align with the changes within in DiSSCo.
Version remains at 0.1.0.

Update TETTRIs Service schema

---

data-model/fdo-type/tettris-service/0.1.0/schema/tettris-service.json

Change enum for status

---

data-model/Dockerfile
data-model/developer-schema/data-mapping/0.3.0/schema/data-mapping-request.json
data-model/developer-schema/machine-annotation-service/0.3.0/schema/machine-annotation-service-request.json
data-model/developer-schema/source-system/0.3.0/schema/source-system-request.json
data-model/fdo-type/data-mapping/0.3.0/schema/data-mapping.json
data-model/fdo-type/data-mapping/0.3.0/schema/default-mapping.json
data-model/fdo-type/data-mapping/0.3.0/schema/field-mapping.json

add requests for 
- source system
- data mapping
- mas
Other changes
- Make fieldMapping and defaultMapping separate objects. slightly messier schema in exchange for much nicer code generated from the schemas, and gives us room to define schemas for these objects later

add requests

---

data-model/developer-schema/data-mapping/0.3.0/schema/data-mapping-request.json
data-model/developer-schema/machine-annotation-service/0.3.0/schema/machine-annotation-service-request.json
data-model/fdo-type/annotation/0.3.0/schema/annotation-target.json

Bug fix/id fix

---

README.md

updated to include a link to the current openDS documentation and github templates

Updated openDS README.md

---

data-model/developer-schema/machine-annotation-service/0.3.0/schema/machine-annotation-service-request-wrapper.json
data-model/developer-schema/machine-annotation-service/0.3.0/schema/machine-annotation-service-request.json

MAS create/update requests now may contain environmental variables and secrets
[See PR on Orchestration Service](https://github.com/DiSSCo/dissco-core-orchestration-backend/pull/46)

mas request wrapper

---

data-model/developer-schema/source-system/0.3.0/schema/source-system-request.json

align with orchestration service

add max records

---

data-model/nginx/nginx.conf

- Content-type to application/json
- Force set encoding to UTF-8

Fix utf 8 encoding and set default content-type to json

---

data-model/fdo-type/annotation/0.3.0/examples/active-annotation-example.json
data-model/fdo-type/annotation/0.3.0/examples/active-deleting-annotation-example.json
data-model/fdo-type/annotation/0.3.0/examples/approved-annotation-example.json
data-model/fdo-type/annotation/0.3.0/examples/rejected-annotation-example.json
data-model/fdo-type/annotation/0.3.0/examples/tombstoned-annotation.json
data-model/fdo-type/annotation/0.3.0/schema/annotation-target.json
data-model/fdo-type/machine-annotation-service/0.3.0/schema/machine-annotation-service.json

dot notation to block notation

dot notation to block notation

---

data-model/fdo-type/data-mapping/0.3.0/examples/data-mapping-example.json
data-model/fdo-type/data-mapping/0.3.0/examples/tombstoned-data-mapping-example.json
data-model/fdo-type/data-mapping/0.3.0/schema/data-mapping.json

example data mapping now adheres to schema

fix example data mapping

---

data-model/fdo-type/machine-annotation-service/0.3.0/schema/machine-annotation-service.json
data-model/fdo-type/shared-model/0.3.0/examples/environmental-variable-example.json
data-model/fdo-type/shared-model/0.3.0/examples/secret-variable.json
data-model/fdo-type/shared-model/0.3.0/schema/environmental-variable.json
data-model/fdo-type/shared-model/0.3.0/schema/secret-variable.json

Discussed over slack:
- add namespace to terms
- align object name with term name
- fix required fields
- move to shared objects to enable other objects to reuse it 
- added examples

Change env and secret for MAS

---

data-model/fdo-type/shared-model/0.4.0/schema/tombstone-metadata.json

Small fix in TombstoneMetadata

Fix additionalProperties/required in relatedPID

---

data-model/fdo-type/digital-media/0.4.0/schema/digital-media.json
data-model/fdo-type/digital-specimen/0.4.0/schema/event.json

Fix version of refs

---

data-model/developer-schema/machine-annotation-service/0.4.0/schema/machine-annotation-service-request.json
data-model/fdo-type/data-mapping/0.4.0/schema/data-mapping.json
data-model/fdo-type/data-mapping/0.4.0/schema/field-mapping.json
data-model/fdo-type/data-mapping/0.4.0/schema/term-mapping.json
data-model/fdo-type/digital-media/0.4.0/schema/digital-media.json
data-model/fdo-type/machine-annotation-service/0.4.0/schema/machine-annotation-service.json

Fix term mapping as it the file was still called fieldMapping
Removed Owner from digital media as it is mapped to an agent

Fix term mapping

---

data-model/fdo-type/digital-specimen/0.4.0/schema/chronometric-age.json

Add field chrono:chronometricAgeProtocol

Add protocol field

---

data-model/fdo-type/machine-annotation-service/0.4.0/schema/machine-annotation-service.json
data-model/fdo-type/source-system/0.4.0/schema/source-system.json

Adds MAS on ingestion terms, as described in our refinement doc
https://docs.google.com/document/d/1GqYf83k5-N7r1kbUrNWxz5JmvVJSy8NOp_vYD4imapc/edit?usp=sharing 
[Jira ](https://naturalis.atlassian.net/browse/DD-1756?atlOrigin=eyJpIjoiYTFiZDk3MjhjZTU0NGVjNjhmOTA3NzUwZjc2YzU1MTUiLCJwIjoiaiJ9)
[Jira](https://naturalis.atlassian.net/browse/DD-1756?atlOrigin=eyJpIjoiYTFiZDk3MjhjZTU0NGVjNjhmOTA3NzUwZjc2YzU1MTUiLCJwIjoiaiJ9)

add mas on ingestion terms
